version: '3.8'

services:
  app:
    container_name: auctionpromax-app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:80"
    working_dir: /var/www/html/auctionpromax
    volumes:
      - ../src:/var/www/html/auctionpromax
      - ./apache/auctionpromax-default.conf:/etc/apache2/sites-available/000-default.conf

  db:
    container_name: auctionpromax-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
